package com.example.Web.System.util.mappers;

import com.example.Web.System.dto.CategoryDTO;
import com.example.Web.System.dto.request.RequestCategorySaveDTO;
import com.example.Web.System.entity.Category;
import org.mapstruct.Mapping;

import java.util.List;

public interface CategoryMapper {
    @Mapping(target = "itemID", ignore = true) // Ignore itemID, it's generated by the database
    @Mapping(target = "activeState", constant = "true") // Set activeState to true by default
    Category requestDtoToEntity(RequestCategorySaveDTO requestCategorySaveDTO);

    List<CategoryDTO> requestEntityListToDtoList(List<Category> items);

    List<CategoryDTO> requestPageToList(List<Category> items);
}